version: '3.8'
services:
  web:
    build: 
      context: ./my-scan
      dockerfile: Dockerfile
    ports:
      - "80:3000"  # ยิงพอร์ต 80 เข้า 3000
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    restart: always

  worker:
    build: 
      context: ./my-scan
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    restart: always

  db:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-scandb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}

volumes:
  postgres_data:
